version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kitty_items
      - POSTGRES_USER=kitty_user
      - POSTGRES_PASSWORD=kitty_password
  flow-demo:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/
      - ./usr/src/app/node_modules
